<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="caex" nsURI="http://www.dke.de/CAEX/300" nsPrefix="caex">
  <eClassifiers xsi:type="ecore:EDataType" name="AttributeDataType" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeFamily" eSuperTypes="#//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeNameMapping" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleAttributeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemUnitAttributeName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleAttribute" lowerBound="1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnitAttribute" lowerBound="1"
        eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refSemantic" upperBound="-1"
        eType="#//RefSemantic" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//AttributeValueRequirement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeDataType" eType="#//AttributeDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refAttributeType" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeLib" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeType" upperBound="-1"
        eType="#//Attribute" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValueRequirement" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ordinalScaledType" eType="#//OrdinalScaledType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nominalScaledType" eType="#//NominalScaledType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unknownType" eType="#//UnknownType"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeMode" eType="#//ChangeMode"
        defaultValueLiteral="state" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Description"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revision" upperBound="-1"
        eType="#//Revision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copyright" eType="#//Copyright"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalInformation"
        eType="#//AdditionalInformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CAEXFile" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superiorStandardVersion"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceDocumentInformation"
        lowerBound="1" upperBound="-1" eType="#//SourceDocumentInformation" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalReference" upperBound="-1"
        eType="#//ExternalReferenceType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceHierarchy" upperBound="-1"
        eType="#//InstanceHierarchy" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceClassLib" upperBound="-1"
        eType="#//InterfaceClassLib" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleClassLib" upperBound="-1"
        eType="#//RoleClassLib" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnitClassLib" upperBound="-1"
        eType="#//SystemUnitClassLib" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTypeLib" upperBound="-1"
        eType="#//AttributeLib" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaVersion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String" defaultValueLiteral="3.00"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CAEXObject" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeMode">
    <eLiterals name="state"/>
    <eLiterals name="create" value="1"/>
    <eLiterals name="delete" value="2"/>
    <eLiterals name="change" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ChangeModeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        transient="true" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cAEXFile" upperBound="-2"
        eType="#//CAEXFile" volatile="true" transient="true" derived="true" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalInterface" eSuperTypes="#//InterfaceClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalInterface" upperBound="-1"
        eType="#//InterfaceClass" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalReferenceType" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceHierarchy" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalElement" upperBound="-1"
        eType="#//InternalElement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceClassLib" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceClass" upperBound="-1"
        eType="#//InterfaceClass" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceClass" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refBaseClassPath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" eType="#//InterfaceClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceClass" upperBound="-1"
        eType="#//InterfaceClass" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceFamily" eSuperTypes="#//InterfaceClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceIDMapping" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleInterfaceID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemUnitInterfaceID"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleInterface" lowerBound="1"
        eType="#//ExternalInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnitInterface" lowerBound="1"
        eType="#//ExternalInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalElement" eSuperTypes="#//SystemUnitClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleRequirements" upperBound="-1"
        eType="#//RoleRequirements" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refBaseSystemUnitPath"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseSystemUnit" eType="#//SystemUnitClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalLink" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refPartnerSideA" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refPartnerSideB" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partnerSideA" lowerBound="1"
        eType="#//ExternalInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partnerSideB" lowerBound="1"
        eType="#//ExternalInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeNameMapping" upperBound="-1"
        eType="#//AttributeNameMapping" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceIDMapping" upperBound="-1"
        eType="#//InterfaceIDMapping" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NominalScaledType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredValue" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrdinalScaledType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredMaxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredMinValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefSemantic" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correspondingAttributePath"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleClassLib" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleClass" upperBound="-1"
        eType="#//RoleClass" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleClass" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalInterface" upperBound="-1"
        eType="#//ExternalInterface" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refBaseClassPath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" eType="#//RoleClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleClass" upperBound="-1"
        eType="#//RoleClass" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleFamily" eSuperTypes="#//RoleClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleRequirements" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalInterface" upperBound="-1"
        eType="#//InterfaceClass" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingObject" eType="#//Mapping"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleClass" lowerBound="1"
        eType="#//RoleClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refBaseRoleClassPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceDocumentInformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastWritingDateTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originProjectID" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originProjectTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originRelease" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originVendor" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originVendorURL" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originVersion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupportedRoleClass" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingObject" eType="#//Mapping"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refRoleClassPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleClass" lowerBound="1"
        eType="#//RoleClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemUnitClassLib" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnitClass" upperBound="-1"
        eType="#//SystemUnitClass" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemUnitClass" eSuperTypes="#//CAEXObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalInterface" upperBound="-1"
        eType="#//InterfaceClass" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalElement" upperBound="-1"
        eType="#//InternalElement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedRoleClass" upperBound="-1"
        eType="#//SupportedRoleClass" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalLink" upperBound="-1"
        eType="#//InternalLink" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseClass" eType="#//SystemUnitClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnitClass" upperBound="-1"
        eType="#//SystemUnitClass" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refBaseClassPath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemUnitFamily" eSuperTypes="#//SystemUnitClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requirements" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Copyright">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeMode" eType="#//ChangeMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeMode" eType="#//ChangeMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Revision" eSuperTypes="#//CAEXBasicObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revisionDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeMode" eType="#//ChangeMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalInformation" eSuperTypes="../../caex.anytype/model/GenericAnyType.ecore#//GenericElement"/>
</ecore:EPackage>
